[env:seeed_xiao_nrf52840]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-mbed-nrf52840
framework = arduino
monitor_speed = 115200

lib_deps =
    arduino-libraries/ArduinoBLE @ ^2.0.2
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ST7735 and ST7789 Library